# Configuration for Alacritty, the GPU enhanced terminal emulator.


# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: "MesloLGS NF"

  # Point size
  size: 12.0
